# Generated by Django 4.0.6 on 2022-07-18 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_remove_book_return_avail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED')], default='BORROWED', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
